#!/usr/bin/env bash
set -e

usage() {
  echo "Usage: gh dependabot <merge|rebase> <pull-request-number>"
  echo
  echo "Will tell dependabot to merge by commenting on the given pull request number."
}

action="$1"

case $action in
merge|rebase)
  ;;
*)
  usage
  exit
  ;;
esac

shift

if [ $# -eq 0 ]; then
  usage
  exit
fi

pr="$1"

gh pr comment "$pr" --body "@dependabot ${action}"
